module.exports = {
  "id":"721e1054692b61fccb61583e8b9e719d5dc917b8",
  "name":"Flow 1",
  "nodes":[
     {
        "id":"b581fa4635ad4f8dcc127dcf5bc5a35b677f5248",
        "name":"StartNode",
        "options":{
           "description":"Every flow can have only one StartNode. This is the starting point for the curve generation.       Connect the trigger output to an value generation node (like TriggerCurveNode).       If you want to realize an infinite curve generation route back the to the trigger input of this node."
        },
        "inputPorts":[
        ],
        "outputPorts":[
           {
              "id":"2a6848861ed431109347187a09e5c51e16caaa7e",
              "label":"trigger",
              "portConnectedToPortId":"b48739a0d99090c8c204596795525a45e7673a31",
              "portType":{
                 "value":0,
                 "type":3,
                 "color":"#888888",
                 "isEditable":false
              },
              "direction":"out"
           }
        ],
        "positionX":480,
        "positionY":180
     },
     {
        "id":"5a82b228351939b5014792d9f295e5d2a223c08a",
        "name":"TriggerCurve",
        "options":{
           "description":"The curve connected to the curveData will be used to generate a new value for this flow.       The value of samplesPerSecond specifies how often per second the value is update.       The length of the curve can be set by the durationMs input."
        },
        "inputPorts":[
           {
              "id":"b48739a0d99090c8c204596795525a45e7673a31",
              "label":"trigger",
              "portConnectedToPortId":"2a6848861ed431109347187a09e5c51e16caaa7e",
              "portType":{
                 "value":0,
                 "type":3,
                 "color":"#888888",
                 "isEditable":false
              },
              "direction":"in"
           },
           {
              "id":"a6a343a7f27f55ba5988b4661ad8725986f93a4a",
              "label":"offset",
              "portConnectedToPortId":"d0a9011abe2b39989a3cce074e753afa4026968b",
              "portType":{
                 "value":0,
                 "type":1,
                 "color":"#64d6c1",
                 "isEditable":true
              },
              "direction":"in"
           },
           {
              "id":"0ad8f2f8ebb8de11ff1295a5504d9488b3ec51dd",
              "label":"scale",
              "portConnectedToPortId":"jwri6cg1un",
              "portType":{
                 "value":1,
                 "type":1,
                 "color":"#64d6c1",
                 "isEditable":true
              },
              "direction":"in"
           },
           {
              "id":"f0f76cb31e7ba14e4aeab866170a3c82eb0751d6",
              "label":"durationMs",
              "portType":{
                 "value":3000,
                 "type":1,
                 "color":"#64d6c1",
                 "isEditable":true
              },
              "direction":"in"
           },
           {
              "id":"474fbae56e447f1b73987dca3e51efc3b169bf15",
              "label":"samplesPerSecond",
              "portType":{
                 "value":20,
                 "type":1,
                 "color":"#64d6c1",
                 "isEditable":true
              },
              "direction":"in"
           },
           {
              "id":"e5f3be703c37c3ab4200fc240f3a27bfef8379aa",
              "label":"curveData",
              "portConnectedToPortId":"hs2r8wyw2pg",
              "portType":{
                 "value":[
                    {
                       "key":0,
                       "value":10
                    },
                    {
                       "key":2,
                       "value":20
                    }
                 ],
                 "type":2,
                 "color":"#6b64d6",
                 "isEditable":false
              },
              "direction":"in"
           }
        ],
        "outputPorts":[
           {
              "id":"9b001e9c94697f307db4ac69e7d5b5c67da8d9c1",
              "label":"trigger",
              "portConnectedToPortId":"c5957aa0ceb1eaf8cbd07212df836f8076c49a25",
              "portType":{
                 "value":0,
                 "type":3,
                 "color":"#888888",
                 "isEditable":false
              },
              "direction":"out"
           },
           {
              "id":"d71ba543a9001865bb284c5ab776313188b6a123",
              "label":"latestValue",
              "portType":{
                 "type":1,
                 "color":"#64d6c1",
                 "isEditable":true
              },
              "direction":"out"
           }
        ],
        "positionX":480,
        "positionY":290
     },
     {
        "id":"58a00d0ab1efc3c22bcbcc2dd2efd63e8d6f21b7",
        "name":"RandomNumber",
        "options":{
           "description":"This node will just output a random number between the minimum and maximum       number specified. You can use it to vary the scale or length of a curve."
        },
        "inputPorts":[
           {
              "id":"2964444e6aed7f8830fa81662434efbf66d8e200",
              "label":"min",
              "portType":{
                 "value":0,
                 "type":1,
                 "color":"#64d6c1",
                 "isEditable":true
              },
              "direction":"in"
           },
           {
              "id":"8356fe70863a712b62bcae3638d941cb3b13727a",
              "label":"max",
              "portType":{
                 "value":1,
                 "type":1,
                 "color":"#64d6c1",
                 "isEditable":true
              },
              "direction":"in"
           }
        ],
        "outputPorts":[
           {
              "id":"d0a9011abe2b39989a3cce074e753afa4026968b",
              "label":"number",
              "portConnectedToPortId":"a6a343a7f27f55ba5988b4661ad8725986f93a4a",
              "portType":{
                 "type":1,
                 "color":"#64d6c1",
                 "isEditable":true
              },
              "direction":"out"
           }
        ],
        "positionX":189.1764705882353,
        "positionY":182.7058823529412
     },
     {
        "id":"9jzo9r31np",
        "name":"Bezier",
        "options":{
           "variables":{
              "points":[
                 0.2,
                 0.2,
                 0.8,
                 0.8
              ]
           },
           "visualisation":"BezierCurve",
           "description":"With this node you can create an array of points based on a bezier curve.       In case you want a decreasing bezier curve set the scale to a negative value.       Choose the number of points high enought that the sampling afterwards will create a smooth output curve."
        },
        "inputPorts":[
           {
              "id":"3f2i2de3he6",
              "label":"NumberOfPoints",
              "portType":{
                 "value":200,
                 "type":1,
                 "color":"#64d6c1",
                 "isEditable":true
              },
              "direction":"in"
           }
        ],
        "outputPorts":[
           {
              "id":"hs2r8wyw2pg",
              "label":"",
              "portConnectedToPortId":"e5f3be703c37c3ab4200fc240f3a27bfef8379aa",
              "portType":{
                 "type":2,
                 "color":"#6b64d6",
                 "isEditable":false
              },
              "direction":"out"
           }
        ],
        "positionX":190.3529411764706,
        "positionY":391.90587930118335
     },
     {
        "id":"svziga6o0o",
        "name":"CurrentValue",
        "options":{
           "description":"This node will access the current value of this node       and send it to the next node. The trigger output is exectued every time       the value changes."
        },
        "inputPorts":[
           {
              "id":"yq768sdkms",
              "label":"FlowIndex",
              "portType":{
                 "value":0,
                 "type":1,
                 "color":"#64d6c1",
                 "isEditable":true
              },
              "direction":"in"
           }
        ],
        "outputPorts":[
           {
              "id":"7qm1gqz6jzu",
              "label":"trigger",
              "portConnectedToPortId":"yp77awo1mw",
              "portType":{
                 "value":0,
                 "type":3,
                 "color":"#888888",
                 "isEditable":false
              },
              "direction":"out"
           },
           {
              "id":"pzj16luwlu",
              "label":"latestMeasurement",
              "portConnectedToPortId":"g1kmrx3ti0b",
              "portType":{
                 "type":1,
                 "color":"#64d6c1",
                 "isEditable":true
              },
              "direction":"out"
           }
        ],
        "positionX":18.941176470588335,
        "positionY":691.6873919062253
     },
     {
        "id":"4ci9q258yjl",
        "name":"JSON",
        "options":{
           "settings":[
              {
                 "name":"JSON",
                 "description":"Template for generating a JSON object from the inputs",
                 "settingType":1,
                 "value":"{}"
              }
           ],
           "variables":{

           },
           "description":"This node generates a JSON output that can be processed from e.g. a MQTT output node."
        },
        "inputPorts":[
           {
              "id":"yp77awo1mw",
              "label":"trigger",
              "portConnectedToPortId":"7qm1gqz6jzu",
              "portType":{
                 "value":0,
                 "type":3,
                 "color":"#888888",
                 "isEditable":false
              },
              "direction":"in"
           },
           {
              "id":"g1kmrx3ti0b",
              "label":"measurement1",
              "portConnectedToPortId":"pzj16luwlu",
              "portType":{
                 "value":0,
                 "type":1,
                 "color":"#64d6c1",
                 "isEditable":true
              },
              "direction":"in"
           }
        ],
        "outputPorts":[
           {
              "id":"wljl2vro8e",
              "label":"trigger",
              "portConnectedToPortId":"unq3iow1q8",
              "portType":{
                 "value":0,
                 "type":3,
                 "color":"#888888",
                 "isEditable":false
              },
              "direction":"out"
           },
           {
              "id":"wdaw8vkp2tl",
              "label":"JSON",
              "portConnectedToPortId":"7f37ic08dot",
              "portType":{
                 "value":{

                 },
                 "type":4,
                 "color":"#ababab",
                 "isEditable":false
              },
              "direction":"out"
           }
        ],
        "positionX":309.7647058823529,
        "positionY":704.3932742591664
     },
     {
        "id":"kjc38ydyg1",
        "name":"MQTT",
        "options":{
           "settings":[
              {
                 "name":"host",
                 "description":"Hostname of the MQTT server",
                 "settingType":1,
                 "value":"localhost"
              },
              {
                 "name":"port",
                 "description":"Port of the MQTT server (usual ports: 1883 (unsecured), 8883 (secured))",
                 "settingType":0,
                 "value":1883
              },
              {
                 "name":"clientId",
                 "description":"Id of the client",
                 "settingType":1,
                 "value":"identifier"
              },
              {
                 "name":"topic",
                 "description":"Topic for the MQTT messages",
                 "settingType":1,
                 "value":"topicname"
              },
              {
                 "name":"user",
                 "description":"Username of the client",
                 "settingType":1,
                 "value":"user"
              },
              {
                 "name":"password",
                 "description":"Password of the client",
                 "settingType":1,
                 "value":"secret"
              }
           ],
           "variables":{

           },
           "description":"The MQTT node is an output node allowing to send JSON data to a MQTT broker.       Use the setting page to specify the credentials for the connection."
        },
        "inputPorts":[
           {
              "id":"unq3iow1q8",
              "label":"trigger",
              "portConnectedToPortId":"wljl2vro8e",
              "portType":{
                 "value":0,
                 "type":3,
                 "color":"#888888",
                 "isEditable":false
              },
              "direction":"in"
           },
           {
              "id":"7f37ic08dot",
              "label":"JSON",
              "portConnectedToPortId":"wdaw8vkp2tl",
              "portType":{
                 "value":{

                 },
                 "type":4,
                 "color":"#ababab",
                 "isEditable":false
              },
              "direction":"in"
           }
        ],
        "outputPorts":[
           {
              "id":"ugtbac00vz9",
              "label":"trigger",
              "portType":{
                 "value":0,
                 "type":3,
                 "color":"#888888",
                 "isEditable":false
              },
              "direction":"out"
           }
        ],
        "positionX":576.5882352941176,
        "positionY":749.5697448474018
     },
     {
        "id":"tztf3vjgcte",
        "name":"Number",
        "options":{
           "description":"This node will just output the number spezified."
        },
        "inputPorts":[
           {
              "id":"3bab5w1alig",
              "label":"number",
              "portType":{
                 "value":1,
                 "type":1,
                 "color":"#64d6c1",
                 "isEditable":true
              },
              "direction":"in"
           }
        ],
        "outputPorts":[
           {
              "id":"jwri6cg1un",
              "label":"",
              "portConnectedToPortId":"0ad8f2f8ebb8de11ff1295a5504d9488b3ec51dd",
              "portType":{
                 "type":1,
                 "color":"#64d6c1",
                 "isEditable":true
              },
              "direction":"out"
           }
        ],
        "positionX":191.17647058823533,
        "positionY":296.3932742591666
     },
     {
        "id":"r82482zgxdm",
        "name":"CurrentValue",
        "options":{
           "description":"This node will access the current value of this node       and send it to the next node. The trigger output is exectued every time       the value changes."
        },
        "inputPorts":[
           {
              "id":"m4c986r149",
              "label":"FlowIndex",
              "portType":{
                 "value":0,
                 "type":1,
                 "color":"#64d6c1",
                 "isEditable":true
              },
              "direction":"in"
           }
        ],
        "outputPorts":[
           {
              "id":"3tt1aibdrpu",
              "label":"trigger",
              "portConnectedToPortId":"6dow411pjc6",
              "portType":{
                 "value":0,
                 "type":3,
                 "color":"#888888",
                 "isEditable":false
              },
              "direction":"out"
           },
           {
              "id":"z53ax4l6qbg",
              "label":"latestMeasurement",
              "portConnectedToPortId":"cf2j9f5clmq",
              "portType":{
                 "type":1,
                 "color":"#64d6c1",
                 "isEditable":true
              },
              "direction":"out"
           }
        ],
        "positionX":40.98642533936668,
        "positionY":826.663944765131
     }
  ]
};
